site_name: Oonchie Woodmansee Piano
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
